    field_types:
      path: fieldtypes
      key: fieldTypes
    field_type:
      desc: GET /schema/fieldtype/[name]
      path: fieldtypes/%{name}
      args:
        - name
      key: fieldType
    dynamic_fields:
      desc: GET /schema/dynamicfields
      path: dynamicfields
      key: dynamicFields
    dynamic_field:
      desc: GET /schema/dynamicfields/[name]
      args:
        - name
      path: dynamicfields/%{name}
      key: dynamicField
    copy_fields:
      path: copyfields
      key: copyFields
