schema:
  base_path: schema
  alias: schema_info
  api:
    info:
      desc: GET /schema
      fetch_key: schema
    name:
      desc: GET /schema/name
      method_name: schema_name
      path: name
      fetch_key: name
    version:
      desc: GET /schema/version
      path: version
      fetch_key: version
    unique_key:
      desc: GET /schema/uniquekey
      path: uniquekey
      fetch_key: uniqueKey
    similarity:
      desc: GET /schema/similarity
      path: similarity
      fetch_key: similarity
    fields:
      desc: GET /schema/fields
      path: fields
      params:
        showDefaults: true
      enum_on: fields
    field:
      desc: GET /schema/fields/[name]
      path: fields/%{name}
      args:
        - name
      params:
        showDefaults: true
      fetch_key: field
    field_types:
      desc: GET /schema/fieldtypes
      path: fieldtypes
      enum_on: fieldTypes
    field_type:
      desc: GET /schema/fieldtype/[name]
      path: fieldtypes/%{name}
      args:
        - name
      fetch_key: fieldType
    dynamic_fields:
      desc: GET /schema/dynamicfields
      path: dynamicfields
      enum_on: dynamicFields
    dynamic_field:
      desc: GET /schema/dynamicfields/[name]
      args:
        - name
      path: dynamicfields/%{name}
      fetch_key: dynamicField
    copy_fields:
      desc: GET /schema/copyfields
      path: copyfields
      enum_on: copyFields
