schema:
  base_path: schema
  methods:
    info:
      desc: GET /schema
      enum_on: schema
    schema_name:
      desc: GET /schema/name
      path: name
      enum_on: name
    version:
      desc: GET /schema/version
      path: version
      enum_on: version
    unique_key:
      desc: GET /schema/uniquekey
      path: uniquekey
      enum_on: uniqueKey
    similarity:
      desc: GET /schema/similarity
      path: similarity
      enum_on: similarity
    fields:
      desc: GET /schema/fields
      path: fields
      params:
        showDefaults: true
      enum_on: fields
    field:
      desc: GET /schema/fields/[name]
      path: fields/%{name}
      args:
        - name
      params:
        showDefaults: true
      enum_on: field
    field_types:
      desc: GET /schema/fieldtypes
      path: fieldtypes
      enum_on: fieldTypes
    field_type:
      desc: GET /schema/fieldtype/[name]
      path: fieldtypes/%{name}
      args:
        - name
      enum_on: fieldType
    dynamic_fields:
      desc: GET /schema/dynamicfields
      path: dynamicfields
      enum_on: dynamicFields
    dynamic_field:
      desc: GET /schema/dynamicfields/[name]
      args:
        - name
      path: dynamicfields/%{name}
      enum_on: dynamicField
    copy_fields:
      desc: GET /schema/copyfields
      path: copyfields
      enum_on: copyFields
